import type { Metadata } from "next";
import "./globals.css";
import HeaderTop from "@/components/layout/header/top/HeaderTop";
import NavBar from "@/components/layout/header/nav/NavBar";
import Footer from "@/components/layout/footer/Footer";
import NavBar1 from "@/components/layout/header/nav/NavBar1";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-100 grid grid-rows-[auto_1fr_auto] min-h-[100dvh] antialiased`}
      >
        <header>
          <HeaderTop />
          <NavBar1 />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
